### ISSUE TITLE
Multiversion image

### ISSUE THREAD

**Issue by artisticcheese** [olljanat/multi-win-version-aspnet#1]
How did you manage to build downlevel version of OS images in `process` isolation?

**Comment by olljanat** [comment]
@artisticcheese it works because on **COPY** direction actually just mounts container file system to host and it does not need to start them (which would fail).

**Comment by artisticcheese** [comment]
You are referencing following path `$env:userprofile.docker\config.json` for configuration file. Is it correct location? It shall be under `$env:ProgramData\docker\config`?

**Comment by olljanat** [comment]
There looks to be small typo on guide. Correct location is ```$env:userprofile\.docker\config.json``` which is config for client (**docker.exe** binary).

```$env:ProgramData\docker\config``` is config for server (**dockerd.exe** binary) which is not interesting for this use case.
